version: "3.8"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  modelo:
      image: felipeleao0902/pondearada3
      build:
        context: ./api
      ports:
        - "8001:8001"
  server:
    image: felipeleao0902/podnerada2-server
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0'
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - modelo

  frontend:
    image: felipeleao0902/ponderada2-frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data: