version: "3.8"

services:
  dba:
    image: postgres:15-alpine
    container_name: dba
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: "user"
       POSTGRES_PASSWORD: "password"
       POSTGRES_DB: "mydb"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-mydb}", "-U", "${POSTGRES_USER:-user}",]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      dba:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
volumes:
  pgdata:
