version: '3.9'

services:
  databse:
    image: postgres
    container_name: v1
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORLD=admin
      - POSTGRES_DB=database
    volumes:
    - pgdata:/data/postgres
volumes: 
  pgdata:
    driver: local

